// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	contact.proto
	message.proto

It has these top-level messages:
	Contact
	Method
	Message
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Contact contains public key 'pubkey' which is used to build
// a cryptographic identity inside the system, and notification
// methods.
type Contact struct {
	Methods []*Method `protobuf:"bytes,1,rep,name=methods" json:"methods,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Contact) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

// Method represents notification method or medium and contains
// protocol identifier and an abstract address, which is the
// unique entity identifier withing specified protocol medium
type Method struct {
	Protocol string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Method) Reset()                    { *m = Method{} }
func (m *Method) String() string            { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()               {}
func (*Method) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Method) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Method) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Contact)(nil), "pb.Contact")
	proto.RegisterType((*Method)(nil), "pb.Method")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x49, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe7,
	0x62, 0x77, 0x86, 0x08, 0x0a, 0xa9, 0x70, 0xb1, 0xe7, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x14, 0x4b,
	0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x71, 0xe9, 0x15, 0x24, 0xe9, 0xf9, 0x82, 0x85, 0x82, 0x60,
	0x52, 0x4a, 0x76, 0x5c, 0x6c, 0x10, 0x21, 0x21, 0x29, 0x2e, 0x0e, 0xb0, 0x39, 0xc9, 0xf9, 0x39,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x62, 0x4a, 0x4a,
	0x51, 0x6a, 0x71, 0xb1, 0x04, 0x13, 0x58, 0x0a, 0xc6, 0x4d, 0x62, 0x03, 0xab, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xfa, 0xc0, 0x80, 0x3e, 0x8c, 0x00, 0x00, 0x00,
}
